name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    # macos runners are the only "standard" runners with arm64 CPU
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          cache-from: ghcr.io/sentry-arm/exim4:latest
          cache-to: type=inline
          context: .
          platforms: linux/arm64
          pull: true
          push: true
          tags: ghcr.io/sentry-arm/exim4:latest
